services:
  postgres:
    image: postgres:17
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
#    volumes:
#      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 128M

  api:
    build:
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "files.pythonhosted.org:167.82.48.223"
        - "pypi.org:167.82.48.223"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    env_file:
     - .env
     - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      extra_hosts:
        - "files.pythonhosted.org:167.82.48.223"
        - "pypi.org:167.82.48.223"
    command: ["watchfiles", "arq app.worker.settings.WorkerSettings", "/app"]
    volumes:
      - .:/app
      - /app/.venv
    healthcheck:
      test: ["NONE"]
    env_file:
     - .env
     - .env.docker
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  postgres_data: