"""auto

Revision ID: 1a3ff7153da0
Revises: 53e995931cf2
Create Date: 2026-09-22 14:23:19.135952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3ff7153da0'
down_revision: Union[str, Sequence[str], None] = '53e995931cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('grounded', sa.Boolean(), nullable=True))
    op.alter_column('analysis_runs', 'hypothesis',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_runs', 'hypothesis',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('analysis_runs', 'grounded')
    # ### end Alembic commands ###
