"""auto

Revision ID: 57c5949371df
Revises: 7f5a630c9ae6
Create Date: 2026-09-09 12:42:37.374532

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "57c5949371df"
down_revision: str | Sequence[str] | None = "7f5a630c9ae6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decisions",
        sa.Column("situation", sa.String(length=255), nullable=False),
        sa.Column("chosen_decision", sa.String(length=255), nullable=False),
        sa.Column("personal_reasoning", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="decisionstatus"), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_decisions_created_at", "decisions", ["created_at"], unique=False)
    op.create_index(op.f("ix_decisions_status"), "decisions", ["status"], unique=False)
    op.create_index(op.f("ix_decisions_user_id"), "decisions", ["user_id"], unique=False)
    op.create_table(
        "decision_runs",
        sa.Column(
            "status", sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="decisionstatus"), nullable=False
        ),
        sa.Column("provider", sa.String(length=255), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("category_text", sa.String(length=255), nullable=True),
        sa.Column("biases_text", sa.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["decision_id"],
            ["decisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_decision_runs_created_at", "decision_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_decision_runs_category_text"), "decision_runs", ["category_text"], unique=False)
    op.create_index(op.f("ix_decision_runs_decision_id"), "decision_runs", ["decision_id"], unique=False)
    op.create_index(op.f("ix_decision_runs_status"), "decision_runs", ["status"], unique=False)
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_column("users", "deleted_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.alter_column("users", "password_hash", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_index(op.f("ix_decision_runs_status"), table_name="decision_runs")
    op.drop_index(op.f("ix_decision_runs_decision_id"), table_name="decision_runs")
    op.drop_index(op.f("ix_decision_runs_category_text"), table_name="decision_runs")
    op.drop_index("idx_decision_runs_created_at", table_name="decision_runs")
    op.drop_table("decision_runs")
    op.drop_index(op.f("ix_decisions_user_id"), table_name="decisions")
    op.drop_index(op.f("ix_decisions_status"), table_name="decisions")
    op.drop_index("idx_decisions_created_at", table_name="decisions")
    op.drop_table("decisions")
    # ### end Alembic commands ###
