"""auto

Revision ID: b5574779c92f
Revises: 57c5949371df
Create Date: 2026-09-11 16:42:55.964310

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5574779c92f"
down_revision: str | Sequence[str] | None = "57c5949371df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "decision_runs", "error", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), existing_nullable=True
    )
    op.drop_index(op.f("idx_decision_runs_created_at"), table_name="decision_runs")
    op.create_index(
        "idx_decision_runs_created_at",
        "decision_runs",
        ["decision_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "decisions",
        "situation",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "decisions",
        "chosen_decision",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1024),
        existing_nullable=False,
    )
    op.alter_column(
        "decisions",
        "personal_reasoning",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=1024),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "decisions",
        "personal_reasoning",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "decisions",
        "chosen_decision",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "decisions",
        "situation",
        existing_type=sa.String(length=1024),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.drop_index("idx_decision_runs_created_at", table_name="decision_runs")
    op.create_index(op.f("idx_decision_runs_created_at"), "decision_runs", ["created_at"], unique=False)
    op.alter_column(
        "decision_runs", "error", existing_type=sa.Text(), type_=sa.VARCHAR(length=255), existing_nullable=True
    )
    # ### end Alembic commands ###
