"""auto

Revision ID: e07144743155
Revises: 1a3ff7153da0
Create Date: 2026-09-23 12:24:53.966945

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e07144743155"
down_revision: str | Sequence[str] | None = "1a3ff7153da0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "analysis_runs",
        "action_plan",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.ARRAY(sa.Text()),
        existing_nullable=True,
        postgresql_using="action_plan::text::text[]",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "analysis_runs",
        "action_plan",
        existing_type=sa.ARRAY(sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
